services:
  web:
    image: python:3.12-slim
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db
    command: >
      sh -c "
        echo 'Applying database migrations...' &&
        alembic upgrade head &&
        echo 'Starting application...' &&
        uvicorn api.main:app --host 0.0.0.0 --port 8000
      "
      

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${PROD_DB_USER}
      POSTGRES_PASSWORD: ${PROD_DB_PASSWORD}
      POSTGRES_DB: ${PROD_DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:
  pg_testdata:

networks:
  backend: